# This file was generated by GoReleaser. DO NOT EDIT.
class TenderlyNext < Formula
  desc "Tenderly helps you observe your contracts in any environment."
  homepage "https://github.com/Tenderly/tenderly-cli"
  url "https://github.com/Tenderly/tenderly-cli/releases/download/v0.1.6/tenderly_0.1.6_Darwin_amd64.tar.gz"
  version "0.1.6"
  sha256 "71718689fefc3b495084a5e6628f300d34a3fe04bee7cd4babbb50dfa24fc19e"

  def install
    bin.install "tenderly"
  end
end
